### PR TITLE
Fix namespace issues in MsSqlPlatform.php

### PR DESCRIPTION
**Pull request by pjedwabny**

### CODE REVIEW

**Comment by mevdschee** [comment]
:+1: Sorry.. I can't merge as I don't have write permissions (anymore)..

**Comment by pjedwabny** [comment]
Ok, thank you. As We need MsSqlPlatform support I would like to ask whether this repo is maintained or perhaps We should concentrate on developing our fork?

**Comment by GabrielAnca** [comment]
Hi! Thanks for your contribution. We do maintain all our repositories so please feel free to contribute to any of them :smiley: 

Your PR looks good to me, but since you change the namespace of MsSqlPlatform that will be a breaking change for existing users so we will have to bump the version to 1.1.0 (I can add a CHANGELOG.md file before creating it).

Anyway, I am afraid I cannot accept the Pull Request if you change the vendor name in composer.json. If you revert that change we will merge it.

Thanks!

**Comment by pjedwabny** [comment]
Of course, I thought for a moment that repo is abandoned. Nevermind, its reverted.

**Comment by GabrielAnca** [comment]
As promised, I merged your PR and added a CHANGELOG. Version 1.1.0 is ready to use.

Thanks a lot for your contribution! 😄

**Pull request merged**
